### ISSUE TITLE
run ingest.py on huntsman data

### ISSUE THREAD

**Issue by lspitler** [AstroHuntsman/obs_huntsman#3]
Modify:
`https://github.com/AstroHuntsman/obs_huntsman/blob/develop/python/lsst/obs/subaru/ingest.py`

So it works on Huntsman data.

Test data available here:
https://github.com/AstroHuntsman/test_metah_data/tree/master/images/fields/Ngc6744/83F011639/20180802T085424

**Comment by danjampro** [comment]
Closing after successful ingest.
